//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class BibliotecaEntities : DbContext
    {
        public BibliotecaEntities()
            : base("name=BibliotecaEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Autor> Autors { get; set; }
        public virtual DbSet<Editorial> Editorials { get; set; }
        public virtual DbSet<Libro> Libroes { get; set; }
    
        public virtual ObjectResult<LibroConsultarPorAutor_Result> LibroConsultarPorAutor(Nullable<int> idAutor)
        {
            var idAutorParameter = idAutor.HasValue ?
                new ObjectParameter("IdAutor", idAutor) :
                new ObjectParameter("IdAutor", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<LibroConsultarPorAutor_Result>("LibroConsultarPorAutor", idAutorParameter);
        }
    
        public virtual ObjectResult<LibroConsultarPorAutorYFecha_Result> LibroConsultarPorAutorYFecha(Nullable<int> idAutor, Nullable<int> fechaPublicacion)
        {
            var idAutorParameter = idAutor.HasValue ?
                new ObjectParameter("IdAutor", idAutor) :
                new ObjectParameter("IdAutor", typeof(int));
    
            var fechaPublicacionParameter = fechaPublicacion.HasValue ?
                new ObjectParameter("FechaPublicacion", fechaPublicacion) :
                new ObjectParameter("FechaPublicacion", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<LibroConsultarPorAutorYFecha_Result>("LibroConsultarPorAutorYFecha", idAutorParameter, fechaPublicacionParameter);
        }
    
        public virtual ObjectResult<LibroConsultarPorEditorial_Result> LibroConsultarPorEditorial(Nullable<int> idEditorial)
        {
            var idEditorialParameter = idEditorial.HasValue ?
                new ObjectParameter("IdEditorial", idEditorial) :
                new ObjectParameter("IdEditorial", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<LibroConsultarPorEditorial_Result>("LibroConsultarPorEditorial", idEditorialParameter);
        }
    
        public virtual ObjectResult<LibroConsultarPorFecha_Result> LibroConsultarPorFecha(Nullable<int> fechaPublicacion)
        {
            var fechaPublicacionParameter = fechaPublicacion.HasValue ?
                new ObjectParameter("FechaPublicacion", fechaPublicacion) :
                new ObjectParameter("FechaPublicacion", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<LibroConsultarPorFecha_Result>("LibroConsultarPorFecha", fechaPublicacionParameter);
        }
    
        public virtual ObjectResult<LibroConsultarPorTitulo_Result> LibroConsultarPorTitulo(string tituloLibro)
        {
            var tituloLibroParameter = tituloLibro != null ?
                new ObjectParameter("TituloLibro", tituloLibro) :
                new ObjectParameter("TituloLibro", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<LibroConsultarPorTitulo_Result>("LibroConsultarPorTitulo", tituloLibroParameter);
        }
    
        public virtual int LibroEliminarPorAutor(Nullable<int> idAutor)
        {
            var idAutorParameter = idAutor.HasValue ?
                new ObjectParameter("IdAutor", idAutor) :
                new ObjectParameter("IdAutor", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("LibroEliminarPorAutor", idAutorParameter);
        }
    
        public virtual int LibroEliminarPorEditorial(Nullable<int> idEditorial)
        {
            var idEditorialParameter = idEditorial.HasValue ?
                new ObjectParameter("IdEditorial", idEditorial) :
                new ObjectParameter("IdEditorial", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("LibroEliminarPorEditorial", idEditorialParameter);
        }
    
        public virtual int LibroInsertar(Nullable<int> idAutor, string tituloLibro, Nullable<int> fechaPublicacion, Nullable<int> idEditorial)
        {
            var idAutorParameter = idAutor.HasValue ?
                new ObjectParameter("IdAutor", idAutor) :
                new ObjectParameter("IdAutor", typeof(int));
    
            var tituloLibroParameter = tituloLibro != null ?
                new ObjectParameter("TituloLibro", tituloLibro) :
                new ObjectParameter("TituloLibro", typeof(string));
    
            var fechaPublicacionParameter = fechaPublicacion.HasValue ?
                new ObjectParameter("FechaPublicacion", fechaPublicacion) :
                new ObjectParameter("FechaPublicacion", typeof(int));
    
            var idEditorialParameter = idEditorial.HasValue ?
                new ObjectParameter("IdEditorial", idEditorial) :
                new ObjectParameter("IdEditorial", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("LibroInsertar", idAutorParameter, tituloLibroParameter, fechaPublicacionParameter, idEditorialParameter);
        }
    }
}
